processes:
  download_sitl:
    command: wget https://firmware.ardupilot.org/Plane/stable/SITL_x86_64_linux_gnu/arduplane -O arduplane
    onfail: arpx_exit_error

jobs:
  download:
    tasks:
      - download_sitl
